### PR TITLE
GCC : added variant to packages for binutils, solve linking time error

### PR DESCRIPTION
**Pull request by alalazo**
Changeset :
- added variants to have conditional dependencies on `binutils`, `libelf` and `isl`
- updated gcc versions
- `specs` now contains a complete dump of the rules (which apparently solves issue #117 on my platform)

Feel free to decline the thing if deemed not useful.

### CODE REVIEW

**Comment by tgamblin** [comment]
@alalazo: Does `isl` need to be a variant?  Or should we just build it by default on 5.0+?  Also, does it make sense to make `libelf` and `binutils` variants?  Do you think people will want to build without them?  Maybe @mplegendre has an opinion on this.

**Comment by mplegendre** [comment]
- I don't know of any advantages to leaving isl out.  If that's true, then I'd assume always enable it on supported gccs.
- I don't know why libelf is sometimes built as part of gcc.  It's not a prereq (https://gcc.gnu.org/install/prerequisites.html). We should probably drop it.
- Binutils is required for a working gcc, I think we should make it always dependent.  There are incompatibilities between some binutil and gcc versions (http://wiki.osdev.org/Cross-Compiler_Successful_Builds), if we wanted to get smart we would encode that compatibility info in the gcc package.

**Comment by alalazo** [comment]
- I am fine removing `libelf`, as @mplegendre suggested. I made it a variant because it was already there
and I didn't want to build it as a dependence.
- I am also fine making `isl` an optional dependence based only on version.

I'll update the branch and commit those two changes asap.

**Comment by alalazo** [comment]
@mplegendre , @tgamblin : regarding the other dependencies (excluding only `binutils`) there is [another approach](https://gcc.gnu.org/wiki/InstallingGCC) that may be considered:
>Alternatively, after extracting the GCC source archive, simply run the `./contrib/download_prerequisites` script in the GCC source directory. That will download the support libraries and create symlinks, causing them to be built automatically as part of the GCC build process. Set `GRAPHITE_LOOP_OPT=no` in the script if you want to build GCC without ISL, which is only needed for the optional Graphite loop optimizations.

I didn't try it yet within spack, but I assume that coding a custom `Stage` object for `Gcc` will just do the trick. This will have the following effect:

- `mpfr`, `gmp`, `mpc` and `isl` will not be dependencies any more. Their version for a given GCC will be fixed and consistent (as the file should be officially maintained by the compiler developers/packagers)
- no module files generated for `mpfr`, `gmp`, `mpc` and `isl`
- the `expand_archive()` method of the custom `Stage` object will trigger a download, which may be somehow unexpected

If you think this modification is worth trying, I may be able to implement something quickly.

**Comment by alalazo** [comment]
`binutils` : I don't have strong opinions on that, but having it optional may permit to use system binutils if present. 

@mplegendre : I agree on getting smart where possible. In case, I guess that the preferred way to express dependencies among ranges is something like:
```
depends_on('binutils@2.23:2.24', when='@4.8:4.8.5')
depends_on('binutils@2.24:2.25', when='@4.9:4.9.3')
...
```
where the `when` ranges should be disjoint, right? Should I start coding something like that for this PR?

**Comment by tgamblin** [comment]
@alalazo: I think just the first two changes (`libelf` and `isl`) is all that's needed for this particular PR.  If you want to add the finer-grains `binutils` rules later, that would be really useful, but I can merge the rest before you do that.

re: having GCC download its own dependencies, it would work if you install on a machine that can reach the internet, but Spack can't automatically mirror the stuff in `contrib/download_prerequisites`.  So the mirror functionality would break for those of us using it.  I think for that reason we should stick to having Spack install the dependencies.

Thanks for all contributions!

**Comment by alalazo** [comment]
@tgamblin , @mplegendre : I have done the changes on `libelf` and `isl`. Tell me if you want to remove the binutils variant. Just for the record, I tried only a couple of builds manually (didn't have time yet to set up a Jenkins job on our local machines to test the package more extensively)

**Comment by tgamblin** [comment]
@alalazo This looks good to me -- I think the level of testing is sufficient... we're trying to get some CI going here for Spack as well, so it'll be tested eventually.

Per @mplegendre's suggestion, can you get rid of the binutils variant?  I think It's risky to build w/o binutils and we've seen a lot of gcc issues resulting from conflicting binutils versions.  I think having the dependency gets that under control, or is at least better than nothing.

To really do this right, I probably should adjust the module support working better, so that binutils ends up in your `PATH` when you load an installed gcc.  That's not for this PR, though.

**Comment by alalazo** [comment]
@tgamblin Should be fine now.

**Comment by tgamblin** [comment]
Thanks!

**Pull request merged**
