### PR TITLE
README.md: trivial typo fix

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@tgamblin You know this went to the develop branch, right? I mention this because the typo still exists on master, and therefore on the main spack Github front page.

**Comment by tgamblin** [comment]
Yeah I was debating doing a hot fix.  However, it also occurs to me that we probably should make develop the default branch.  Master is for stable releases but releases are infrequent, and develop is way better than master at the moment.  

Any thoughts on this?  Do other projects do this?

**Comment by jsquyres** [comment]
Everyone has their own religion about branching.

My $0.02: it sounds like your "master" is really a release branch.  Many people associate "master" with current development, so you *might* want to consider the following:

* Rename the current `master` -> `release`
* Rename the current `develop` -> `master`

Again, this is just my $0.02 in a world of many opinions... feel free to ignore...

**Comment by tgamblin** [comment]
I just went with [git flow](http://nvie.com/posts/a-successful-git-branching-model/), which seemed sensible at the time.  In the interest of not disrupting too many people, I just changed the default branch on github to `develop`, so now the most recent activity is at the forefront.  I like that b/c otherwise it looks like we stopped developing at the last release.

Your naming scheme certainly makes more intuitive sense... maybe I'll eventually transition to that.

**Pull request merged**
