### PR TITLE
package files for libuuid, needed for flux and taskwarrior packages

### PR DESCRIPTION
**Pull request by trws**
Also packages for taskwarrior and its sync daemon.

### CODE REVIEW

**Comment by tgamblin** [comment]
I suspect these builds work -- so I'll merge them. But note that `std_cmake_args` includes -DCMAKE_BUILD_TYPE=RelWithDebInfo.  I should probably adapt the cmake executable to notice that you replaced some of the default args.

**Comment by trws** [comment]
Good to know, I'll avoid that in future.  For cmake it might make sense 
to have the standard options, or at least the standard defines, be a 
dict also, since the standard form for options is key-value to begin 
with.  That would make it easy to override specific defaults without 
having to do partial string matching against the list.

**Comment by tgamblin** [comment]
That is actually a really good point.  The only reservation I have about that is that it means you have to learn something new to use cmake.  I think there is probably some good, clean way to do this where people used to shell-ish syntax could still get by...

**Comment by trws** [comment]
There's no reason the current syntax would necessarily have to go away, in fact it would probably be best as an alternative or enhancement rather than a replacement.  I'm thinking something along the lines of adding a catch-all dict argument for un-specified keywords, then a user can splat in a dict or just add keyword arguments to get to the same place.  Something vaguely like this?

```python
def cmake(<existing args>, *verbatim_command_parts, **defines):
  cmd += verbatim_command_parts
  for k, v in defines.iteritems():
    cmd += ["-D{key}={value}".format(key=k, value=v)]
  ...
# Usage
std_cmake_arg_dict['CMAKE_BUILD_TYPE'] = 'Debug'
cmake('-GNinja', CMAKE_PKG_ARG='/usr', **std_cmake_arg_dict)
```

**Comment by tgamblin** [comment]
Yep.  The tricky part of that is that `cmake` there is an `Executable`, so it already has keyword args like `return_output`, `fail_on_error`, and `error`:

https://github.com/scalability-llnl/spack/blob/master/lib/spack/spack/util/executable.py

I would need to rework that class a bit.  Another place this is used is `make(parallel=False)`, although that is actually particular to `make`.  For `cmake` I'd need to decide whether the kwargs should override the three inherited from `Executable`.

**Pull request merged**
