### PR TITLE
Added packaging files for ATLAS with and without netlib's LAPACK

### PR DESCRIPTION
**Pull request by kev40293**
I've created packaging scripts for the ATLAS library, one as a standalone, and the other built using netlib's lapack library.

### CODE REVIEW

**Comment by tgamblin** [comment]
Cool!  You can get to a dependency's prefix with `spec['depname']`, so here it'd be `spec['lapack']`.  There's a bit more about that in the packaging guide, under install environment, prefix objects, and spec objects: http://scalability-llnl.github.io/spack/packaging_guide.html

**Comment by kev40293** [comment]
Thanks that worked. I was able to get spack to build and install LAPACK using the installed ATLAS libs.

**Comment by tgamblin** [comment]
Great!  Let me see if I can get this built at LLNL, and I can then merge your feature in.  I may need to get access to a node that doesn't have frequency throttling, so I may not get back to you until tomorrow.

Is the atlas-lapack package needed anymore?  What about the FIXME comments?

**Comment by kev40293** [comment]
sounds good. Since the lapack build works with an installed atlas, the lapack-atlas package is probably unecessary and could be removed. I should have removed all the FIXME comments from the atlas and lapack packages, except for the header because I'm not sure exactly what to put there.

**Comment by tgamblin** [comment]
This is integrated into develop, and integrated with Ben and Saravan's PRs.  I cannot get ATLAS to build right on our machines, so I've commented out `provides('blas')` until I can actually test it.  But it is there and you can make it resolve `blas` dependencies by uncommenting that.

**Comment by tgamblin** [comment]
Thanks for sending the PR!

**Pull request closed without merging**
